### ISSUE TITLE
[Request] Baubles mod support ~

### ISSUE THREAD

**Issue by PorPit** [AuraDevelopmentTeam/InvSync#22]
can u support Baubles mod?
save Baubles slots item to database~
That would be useful
[Baubles mod](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294623-baubles-1-3-11-1-4-5-updated-2017-5-25)
[slots image](http://i4.piimg.com/508137/e0f3cd8858e88177.png)

**Comment by BrainStone** [comment]
Damn, I hoped that it would work with Baubles. I will definetly try to get it to work.

**Comment by PorPit** [comment]
Okay, I'm looking forward to updating

**Comment by Fungie2134** [comment]
Posting here because the request is the same, but for Galacticraft support.

**Comment by BrainStone** [comment]
@Fungie2134 would you mind providing a link? And a brief description as to where I can find these slots, as I don't know the mod.

Thanks!

**Comment by Fungie2134** [comment]
@BrainStone, not at all ! 
The link : https://micdoodle8.com/mods/galacticraft
I'll search those slots in the meantime.

**Comment by BrainStone** [comment]
Finally implemented

**Comment by PorPit** [comment]
wow. nice

**Comment by BrainStone** [comment]
You can test it with this version. Though be advised that it's not production ready and needs further test and improvements. https://maven.project-creative.de/repository/auradev-snapshots/world/jnc/invsync/InvSync/0.6.19.239-modules-DEV/InvSync-0.6.19.239-modules-DEV.jar

The syncing is working as far as I tested it, I just can't gurantee at this point that there aren't any major bugs that cause the plugin to break or data corruption.
Also note that it doesn't migrate existing data yet.

I'd love to hear back from you if it's working or not, but don't blame me if it fucks up your data when used in production.

It's ready to be used in production when verision 0.7.0 gets released to ore.

**Comment by BrainStone** [comment]
@Aang23 please create a separate feature request for galacti craft.
