### ISSUE TITLE
should add save player inventory task

### ISSUE THREAD

**Issue by PorPit** [AuraDevelopmentTeam/InvSync#23]
if server was crash and  shut down

player inventory data cant save to database

some player's inventory data will back to long time ago

u should add save player inventory task

Such as when the world is saving(SaveWorldEvent),to save online player  inventory data

**Comment by BrainStone** [comment]
The problem is, that in most cases the server crashes it still shuts down the plugins. If it does that you don't have to worry.

But if it doesn't shut down the plugins then there's nothing I can do. My apologies. The only thing I could imagine is saving the inventory regularly.
