### ISSUE TITLE
Using with 1.11.2

### ISSUE THREAD

**Issue by yodaa59** [AuraDevelopmentTeam/InvSync#25]
Hello,

It is possible to use your plugin with minecraft 1.11.2 ? 

Thanks for reply :)

**Comment by BrainStone** [comment]
Have you tried using it on 1.11.2?  
If that doesn’t work, then I think it won’t. As I won’t backport the plugin. My apologies

**Comment by BrainStone** [comment]
Feel free to reopen this issue if the it doesn't work.
