### ISSUE TITLE
How to use h2 absolute path ?

### ISSUE THREAD

**Issue by 879492767** [AuraDevelopmentTeam/InvSync#26]
#### Issue Description:
because no matter how I set up, it can't connect to MySQL.

#### What happens:
can't use mysql ,but h2 is ok. other plugins can use mysql.

#### What you expected to happen:
I want to use mysql or use h2 to make two server Inventory  synchronize.

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- InvSync-0.6.17
- spongeforge-1.12.2-2611-7.1.0-BETA-2955 
- Other related mods: flexiblelogin-0.16.8 chatmanage holograms-3.1 griefprevention-1.12.2-4.3.0.526 LuckPerms-Sponge-4.1.20 NewHonor Nucleus-1.2.2-S7.0-MC1.12.2-plugin PixelAutoMessages-1.0.2-b11 PlaceholderAPI-4.4 projectcore-7.0.0-0.2.1 VirtualChest-0.4.8

#### Your most recent log or stack trace file where the issue was present: 

[pastebin/gist/etc link here]

```
[Or stack trace here (Remove this if you don't put anything here!)]
```

**Comment by BrainStone** [comment]
Just use an absolute path. Or symlinks.

What error did you get when trying to connect to MySQL?

**Comment by 879492767** [comment]
It's totaleconomy's config,can use MySQL. 
currency {
    dollar {
        currency-plural=Dollars
        currency-singular=Dollar
        default=true
        prefix-symbol=true
        startbalance="100"
        symbol="$"
        transferable=true
    }
}
database {
    enable=true
    password="5678900"
    url="mysql://localhost:3306/minecraft"
    user="root"
}

It's invsync's config, I can't use it. Invsync don't create a table in MySQL.
storage {
    # The stoage engine that should be used
    # Allowed values: h2 mysql
    storageEngine="MySQL"
    
    # Settings for the h2 storage engine
    h2 {
        # Where the databaseFile will be stored. Can be a relative or absolute path.
        # An absolute path is recommended when using this to synchronize over several servers
        databaseFile="URLs=jdbc:h2://D:\inventoryStorage.db"
    }
    
    # Settings for the MySQL storage engine
    MySQL {
        # Host of the MySQL-Server
        host="localhost"
        # Port of the MySQL server. Default: 3306
        port=3306
        # The database to store in
        database="minecraft"
        # The user for the database
        user="root"
        # Password for that user
        password="5678900"
        # Prefix for the plugin tables
        tablePrefix="invsync_"
    }
}

**Comment by 879492767** [comment]
![image](https://user-images.githubusercontent.com/37323543/37551506-cd51fd9e-29db-11e8-8bf4-7d82af99ba67.png)
And this is my MySQL.

**Comment by 879492767** [comment]
[12:11:11] [Server thread/ERROR] [Sponge]: Could not pass FMLInitializationEvent to Plugin{id=invsync, name=Inventory Sync, version=0.6.17, description=This plugin synchronizes the player inventory with a database, url=https://github.com/BrainStone/InvSync, authors=[The_BrainStone], source=D:\服务端测试\1.12.2\mods\InvSync-0.6.17.jar}
java.lang.IllegalArgumentException: Invalid storage Engine!

**Comment by 879492767** [comment]
Change MySQL to mysql, It creates a table, but..
[12:17:51] [Server thread/WARN]: Failed to save player data for _callme

**Comment by 879492767** [comment]
I succeeded. There were some small problems in config. This is a good plugins.

**Comment by BrainStone** [comment]
Glad you got it working!
