### ISSUE TITLE
[Request] Tough As Nails mod support ~

### ISSUE THREAD

**Issue by OldKingisdie** [AuraDevelopmentTeam/InvSync#27]
#### Issue Description:

I need you help to  the support the【Tough As Nails】 mod 

including thirst, body temperature。

and this Extra Bit Manipulation

There is a armor fence like Bauble

https://github.com/Glitchfiend/ToughAsNails
https://github.com/Phylogeny/ExtraBitManipulation

**Comment by BrainStone** [comment]
I have tried looking into Baubles etc and it's definately not easy to access that data from a plugin. I'll finish Baubles first and if the system is portable to Tough As Nails and Extra Bit Manipulation I'll add it too.

**Comment by OldKingisdie** [comment]
OK，thank you very much～～

**Comment by BrainStone** [comment]
Working
