### ISSUE TITLE
SQL Manager.

### ISSUE THREAD

**Issue by AceGamer45** [AuraDevelopmentTeam/InvSync#28]
#### Issue Description:
Since the new version of sponge, there are problems with the database

#### What happens:

The plugin is no longer functional since the new version of sponge, several plugin using a database are also affected by that like EconomyLite. https://github.com/Flibio/EconomyLite/issues/90

#### Steps to reproduce:

1. start server

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- InvSync: 0.6.17
- Sponge: 1.12.2-2705-7.1.0-BETA-3361 
- Other related mods: 

#### Your most recent log or stack trace file where the issue was present: 

https://pastebin.com/3BBtDku1
(There is also the EconomyLite problem, you have to go a little lower for InvSync)

```
[Or stack trace here (Remove this if you don't put anything here!)]
```

**Comment by BrainStone** [comment]
In the log I can only see warnings about connection leaks. Nothing that would indicate a non-working plugin

**Comment by AceGamer45** [comment]
I just did some tests again, it's just that the inventory is not the same by passing from one server to another but it may be due to the configuration of my server, I would do other tests, but I still get this message when I start the server, it fixes?

**Comment by BrainStone** [comment]
The message about the connection leaks can be ignored. And won’t go away.

If you can show me other errors or similar, let me know.

Also keep in mind that users need permissions for their inventories to sync properly.
