### ISSUE TITLE
Issue connecting to db

### ISSUE THREAD

**Issue by AhmiDarrow** [AuraDevelopmentTeam/InvSync#30]
#### Issue Description:
Having issue having inventorysync connect correctly to the db at least I think that is the issue.

#### What happens:
https://pastebin.com/hAMytgRJ

#### Steps to reproduce:

1. start server 

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- InvSync: InvSync-0.6.17
- Sponge: spongeforge-1.12.2-2705-7.1.0-BETA-3361
- Other related mods: 

#### Your most recent log or stack trace file where the issue was present: 

https://pastebin.com/hAMytgRJ

**Comment by BrainStone** [comment]
That’s an interesting error for sure. I’ll investigate when I’m home.

**Comment by BrainStone** [comment]
Are you using MySQL 8?

**Comment by AhmiDarrow** [comment]
I was, I have since switched to MariaDB for overall better experience. Though I have not tried to use a bungee cord setup again due to seeming unreliability of being able to sync the inventories. But I can set one back up if you think this may give a resolution as to what caused this error.

**Comment by BrainStone** [comment]
Well, it seems like just MySQL 8 is the issue. Older versions and MariaDB will work fine

**Comment by BrainStone** [comment]
I'll close this, as I'm just using Sponge's database API. Meaning when it's fixed in Sponge, it'll be fixed in InvSync too
