### ISSUE TITLE
Permissions don't work - without permissions mod

### ISSUE THREAD

**Issue by daniel-widrick** [AuraDevelopmentTeam/InvSync#35]
#### Issue Description:
I run a sponge forge server (network under velocity) with the Foolcraft3 pack. Without a permissions mod, the invsync defaults all non-op players to having no permissions. this means players can't sync inventories between our two servers.

To get this to work for our use case I had to modify the snapshot code:
src/main/java/world/jnc/invsync/util/serializer/module/BaseSyncModule.java line 72
return isEnabled();

We removed all player based checks and this works for our specific use case.

I have not tested this with a permissions plugin... we don't currently run one.

#### What happens:
Use plugin without permissions plugin. All non-op players don't have permission to inventory sync.

#### What you expected to happen:
Use plugin without permissions plugin. Plugin syncs any modules set to "enabled" in the config.

#### Steps to reproduce:

1. two spongeforge servers
2. no permissions plugins
3. enable desired modules
4. join as non op.
5. join other server: debug: true shows hasPermission: false (might not be exact error text)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.x
- InvSync: InvSync-0.6.19.294-SNAPSHOT.jar all the way back to atleast sep 2018 release
- Sponge: spongeforge-1.12.2-2768-7.1.5.jar
- Other related mods: Foolcraft 3 Pack - I don't think it was related. (we pull out clump mod and add dynmap)

#### Your most recent log or stack trace file where the issue was present: 

I don't have this info... I think the issue is described adequately above.

------------------

I may have missed how to configure the permissions listed in the README.md either in the plugin.conf or sponge/global.conf but that information was not readily apparent in the documentation if so.

**Comment by BrainStone** [comment]
The solution is to use a permissions plugin. Which you really should have.
And it's indeed intended that players don't sync inventories when they don't have permissions.

And lastly as far as I know you cannot make permissions default to true for non-OPs as you can on Bukkit. So there's nothing that can be done here.

**Comment by daniel-widrick** [comment]
Ok. What you're saying makes sense and I'm pretty new to sponge development (Days) but let run this by you for your thoughts:

How would you feel about adding a config parameter, call it "usePermissionsPlugin" default it to true then in the /src/main/java/world/jnc/invsync/util/serializer/module/BaseSyncModule.java file Run an if statement against the new config value.

If said config value is true: operate exactly as it does now
If said config value has been changed to false: disregard the permissions and only return the result of isEnabled()

----

I think there's a definite use case for this plugin in VERY simple setups that would benefit from not being tethered to the complication of an intense permissions system... Perhaps I'm  totally off base in that thinking?

**Comment by BrainStone** [comment]
Trust me, you'll be spending more time implementing this, than setting up a permissions plugin. Which in the case of LP is less than 5 minutes for a very basic setup. Even for beginners.

That being said, I would not approve of a PR adding such a config option, as I think the long term maintenace burden is more than the benefit

**Comment by BrainStone** [comment]
Ok. Turns out there is a way to set default permissions. I quickly threw a test together, which I was not able to test myself. But go ahead and try it for yourself and see if you have the sync permissions without a permissions plugin available.

Try this file: https://maven.project-creative.de/repository/auradev-snapshots/world/jnc/invsync/InvSync/0.6.19.295-default-permissions-DEV/InvSync-0.6.19.295-default-permissions-DEV.jar
