### ISSUE TITLE
Add Thaumcraft 6 Player data support

### ISSUE THREAD

**Issue by phillipinman** [AuraDevelopmentTeam/InvSync#38]
Hi,

First thank you for your work, it's greatly appreciated. This plugin makes everything possible on our server :)

I was wondering if it would be possible to add thaumcraft support by storing it's Playerdata in the database to support cross server play? I imagine this isn't easy but thought I'd ask. The items themselves work across servers but the player data does not.

Many thanks for your work :)

**Comment by BrainStone** [comment]
I will look into it. Though I think it should be possible. And if TC6 does it right, it’s actually trivial. I’d be surprised if it didn’t do it that way btw.

And in case you didn’t know, I do have a Patreon page.

**Comment by phillipinman** [comment]
Thank you. :)

And I did not know that, I'll be sure to check that out, I'm sure I can find it on the sponge ore page :)

**Comment by BrainStone** [comment]
You should be able to find it there. If not, let me know.

**Comment by phillipinman** [comment]
All good, donated ;)

**Comment by BrainStone** [comment]
Thank you. Much appreciated!

**Comment by BrainStone** [comment]
@phillipinman can you try this version: https://maven.aura-dev.team/repository/auradev-snapshots/world/jnc/invsync/InvSync/0.6.20.321-DEV/InvSync-0.6.20.321-DEV.jar ?

**Comment by phillipinman** [comment]
I certainly can, I don't have an ETA but I'll setup a test server sometime this week and let you know :)

**Comment by phillipinman** [comment]
What exactly does it sync out of curiousity? I assume all research and player related stats?

**Comment by BrainStone** [comment]
It syncs research/knowledge and warp.

**Comment by BrainStone** [comment]
Since I haven't heard back anything, I'm assuming it works.
