### ISSUE TITLE
Add ability to set a auto-save timer

### ISSUE THREAD

**Issue by allenclan23** [AuraDevelopmentTeam/InvSync#44]
Just as the title says, i'd like to see a feature of allowing server owners to set a time on which the plugin will auto-save the inventories to the database.

**Comment by bluelightning32** [comment]
I've seen a lot of commits about this feature. How close is it to being done? Should we start trying it out and looking for bugs?

**Comment by BrainStone** [comment]
Should be done by now. Forgot to close the issue.
