### ISSUE TITLE
Seperate Inventories Not Syncing

### ISSUE THREAD

**Issue by Dgretty** [AuraDevelopmentTeam/InvSync#47]
#### Issue Description:
I have 2 seperate servers, Plugin loads fine with no errors, but when going between the servers they are not syncing. And i have 2 seperate inventories. I have setup the Databases and table correctly. And was working until i did a restart.

#### Steps to reproduce:

1. Start server 1
2. Start server 2
3. Fill inventory on server 1
4. Move to server 2
5. Items on server 1 do not get transferred to server 2
...

____
#### Affected Versions (Do *not* use "latest"):

- Paper 1.14.3 ver 129
- InvSync: 109b

#### Your most recent log or stack trace file where the issue was present:

No Errors

```

**Comment by BrainStone** [comment]
You have the wrong plugin. This is a Sponge plugin. And has nothing to do with the Spigot plugin, except that they share the name.
