### ISSUE TITLE
[FEATURE] Reskillable

### ISSUE THREAD

**Issue by robertdrakedennis** [AuraDevelopmentTeam/InvSync#50]
#### Issue Description:

Looking to possibly get this: https://www.curseforge.com/minecraft/mc-mods/reskillable mod added to inventory sync support as it has gotten quite popular and used commonly with Tough as Nails. 

Appreciate it!

**Comment by tyon2006** [comment]
I would really appreciate this integration as well! Thanks!

**Comment by BrainStone** [comment]
A little update on this is that after a talk with the author it's possible to do with my standard way. So this will likely need to wait for a while.

**Comment by BrainStone** [comment]
I took a look and it looks like it's trivial by now. See commit 350af7ebb647ea0cbe8bac8218be9cc08d251283

Try this version and let me know if it works: https://maven.aura-dev.team/repository/auradev-snapshots/world/jnc/invsync/InvSync/0.6.20.339-reskillable-DEV/InvSync-0.6.20.339-reskillable-DEV.jar

**Comment by BrainStone** [comment]
Implemented by a3b9aca99042eda7832b835ddc4820fb002f62b1
