### ISSUE TITLE
Can't connect to external database

### ISSUE THREAD

**Issue by LuxusDarkangel** [AuraDevelopmentTeam/InvSync#54]
#### Issue Description:

I'm trying to connect to an external db but InvSync keeps trying to use my localhost address instead of the one I set in the config file.

#### What happens:

It tries to connect to the right db but on the wrong IP.

#### What you expected to happen:

It connects to the right IP

#### Steps to reproduce:

1. Change config to use an external mariadb database.
2. Start the server.
3. Check the IP it's trying to connect to in the log file.

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- InvSync: release 0.6.19.318 and snapshot 0.6.20.345.
- Sponge: spongeforge-1.12.2-2838-7.2.1

#### Your most recent log or stack trace file where the issue was present:

https://gist.github.com/LuxusDarkangel/8be7e7dc9f6e9b471b53e39bdd9b7a1f

**Comment by BrainStone** [comment]
https://gist.github.com/LuxusDarkangel/8be7e7dc9f6e9b471b53e39bdd9b7a1f#file-gistfile1-txt-L87

**Comment by LuxusDarkangel** [comment]
Yeah, and this is my config file:
host="51.75.25.191"

log:
'serversync'@'143.131.218.229'

**Comment by BrainStone** [comment]
The ``143.131.218.229`` is the client IP. Not the server IP.

**Comment by LuxusDarkangel** [comment]
Oh you're right, I simply didn't grant permissions to my IP on mariadb. I don't remember having to do that before tho, I guess the standard security changed since then.

Thank you very much! ^^

**Comment by BrainStone** [comment]
by default only local connections are allowed (aka `127.0.0.1`). Or you grant for every IP with `%`
